version: '3.4'

services:
  gateway:
    image: 333490196116.dkr.ecr.ap-south-1.amazonaws.com/teamteach-gateway
    container_name: teamteach-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
