server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 

ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000  
  eureka:
    enabled: false

zuul:
  host: 
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    users:
      path: /users/**
      sensitiveHeaders:
      url: http://localhost:8081/users
    profiles:
      path: /profiles/**
      sensitiveHeaders:
      url: http://localhost:8082/profiles
    journals:
      path: /journals/**
      sensitiveHeaders:
      url: http://localhost:8083/journals
    files:
      path: /files/**
      sensitiveHeaders:
      url: http://localhost:8084/files
    users-docs:
      sensitiveHeaders:
      url: http://localhost:8081
    profiles-docs:
      sensitiveHeaders:
      url: http://localhost:8082
    journals-docs:
      sensitiveHeaders:
      url: http://localhost:8083

spring:
  application:
    name: zuul-server
